# Program Behavior
profile=high-quality

# Video
vo=gpu-next
vf=d3d11vpp=w=0:h=0:scaling-mode=nvidia # NVIDIA RTX Super Resolution
hwdec=nvdec-copy

correct-pts=yes
hr-seek=yes
hr-seek-framedrop=no

# Playback Control
pause=yes

# Watch Later
save-position-on-quit=yes

# GPU Renderer
interpolation=yes
tscale=oversample

# Video Sync
video-sync=display-resample

# Track Selection
slang=chs,sc,zh,chi,eng
alang=en,chi

# Subtitles
sub-auto=fuzzy
sub-font="Microsoft YaHei UI Bold"
sub-spacing=0.5

# Window
autofit-larger=70%x70%
