profile=high-quality

# Video
vo=gpu-next
hwdec=auto

# Video Sync
video-sync=display-resample

# GPU
interpolation=yes
tscale=oversample

# Track Selection
slang=chs,sc,zh,chi,eng
alang=en,chi

# Subtitles
sub-auto=fuzzy
sub-font="Microsoft YaHei UI Bold"
sub-spacing=0.5

# Window
autofit-larger=70%x70%

# Watch Later
save-position-on-quit=yes
